

# ===============================
name: Release Stremio Addon

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (e.g., v1.0.1)'
        required: false
        type: string

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: |
          if [ -f package.json ]; then
            npm test || echo "No tests defined."
          fi

      - name: Build (if applicable)
        run: |
          if [ -f package.json ]; then
            npm run build || echo "No build step defined."
          fi

      - name: Generate release notes
        id: changelog
        run: |
          echo "Generating release notes..."
          VERSION="${{ github.ref_name }}"
          if [ -f CHANGELOG.md ]; then
            awk "/^## \[${VERSION#v}\]/{flag=1;next}/^## \[/{flag=0}flag" CHANGELOG.md > release_notes.md
          else
            echo "## What's New in $VERSION" > release_notes.md
          fi
          if [ ! -s release_notes.md ]; then
            echo "## What's New in $VERSION" > release_notes.md
            echo "- Updates and improvements" >> release_notes.md
          fi
          echo "" >> release_notes.md
          echo "## 🚀 Installation" >> release_notes.md
          echo "" >> release_notes.md
          echo "- Deploy to your own server or use the public instance if available." >> release_notes.md
          echo "- See [README.md](./README.md) for deployment and usage instructions." >> release_notes.md
          echo "" >> release_notes.md
          echo "## 📖 Documentation" >> release_notes.md
          echo "- [Installation Guide](./docs/installation.md)" >> release_notes.md
          echo "- [Usage Guide](./docs/usage.md)" >> release_notes.md
          echo "- [Troubleshooting](./docs/troubleshooting.md)" >> release_notes.md
          echo "- [FAQ](./docs/faq.md)" >> release_notes.md
          echo "✅ Release notes generated"

      - name: Create release package
        run: |
          echo "Creating release package..."
          mkdir -p package
          cp -r README.md LICENSE CHANGELOG.md package/ 2>/dev/null || true
          cp -r docs/ package/ 2>/dev/null || true
          cp -r vlsubcom.lua package/ 2>/dev/null || true
          cp -r scripts/ package/ 2>/dev/null || true
          cp -r server.js config.js package.json package-lock.json package/ 2>/dev/null || true
          cd package
          zip -r ../stremio-addon-${{ github.ref_name }}.zip . -x "*.DS_Store" "*/.*"
          cd ..
          echo "✅ Package created: stremio-addon-${{ github.ref_name }}.zip"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: "Stremio Subtitle Addon ${{ github.ref_name }}"
          body_path: release_notes.md
          draft: false
          prerelease: false
          files: |
            stremio-addon-${{ github.ref_name }}.zip
            README.md
            LICENSE
            CHANGELOG.md
            docs/**
            vlsubcom.lua
            scripts/**
            server.js
            config.js
            package.json
            package-lock.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Verify release
        run: |
          echo "🎉 Release created successfully!"
          echo ""
          echo "📦 Release assets:"
          echo "  - stremio-addon-${{ github.ref_name }}.zip (Complete package)"
          echo "  - README.md, LICENSE, CHANGELOG.md, docs/, scripts/, server.js, config.js, package.json, package-lock.json, vlsubcom.lua"
          echo ""
          echo "🔗 Release URL: https://github.com/${{ github.repository }}/releases/tag/${{ github.ref_name }}"
          echo ""
          echo "✅ Stremio Addon release workflow completed."